server:
  port: 7087
spring:
  application:
    name: fang-seata-account
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fang_local?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml

#seata:
#  enabled: true
#  application-id: seata-server
#  tx-service-group: fsp_tx_group
#  enable-auto-data-source-proxy: true
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: localhost:8848
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: localhost:8848
#      namespace:
#      userName: "nacos"
#      password: "nacos"