server:
  port: 9201



spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 6000
    database: 0
#统一配置跨域请求：
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
